### PR TITLE
Implement "Crypto" interface, remove duplicate code

### PR DESCRIPTION
**Pull request by davidebeatrici**
This commit implements a `Crypto` interface, which allows to operate the various cryptographic libraries in a single, generic way.

There are several advantages provided by this concept:

- Duplicate code is almost non-existent.
- Consistency is guaranteed for certain aspects of the code, as long as the code style is the same across all files.
- No limitations for what can be done inside a cryptographic implementation. NSS and wolfCrypt are two great examples, because they need a longer initialization procedure.
- Performance appears to be unaltered!

### CODE REVIEW

**Review by Avatat — APPROVED** [review]
I really like these changes!
They will help me in adding the next features - a progress status and AEGIS algorithm :)

**Review by Krzmbrzl — APPROVED** [review]
I haven't really looked at the details of implementation for each crypto library as you know these way better than me, but overall these changes seem very robust to me.

The only thing I was wondering was whether the time in seconds (I guess as a double and thus also in fractions of a second?) is accurate enough. I would have expected microseconds for benchmarking code. Also in principle we should use a monotonic clock for this. I don't know whether the `seconds()` function does that already, but I also couldn't quickly find how to use a monotonic clock in C on the internet. My guess'd be that plain C doesn't support that so we need external libs :shrug:

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/crypto-benchmark/blob/efa8a31d21da9267336dd954e4253a63678e14ab/utils.c#L9-L17

Monotonic, nanosecond resolution.

**Comment by Krzmbrzl** [comment]
Ah okay. And I was wondering where the `seconds` function was coming from :facepalm:

**Comment by Krzmbrzl** [comment]
Why are the CIs failing though?

**Comment by davidebeatrici** [comment]
Because benchmarks take too much time on the ARM64 builders, thus Travis CI assumes the program is stuck because there's no output at all for 10 minutes.

@Avatat is working on a nice solution: we print every ~10 seconds a status update.

**Comment by davidebeatrici** [comment]
However, this failure is weird: there's no output at all.

Seems to be a temporary issue on Travis CI, it randomly happened across the past few builds...

I restarted the builds, they're now green.

**Pull request merged**
